### ISSUE TITLE
Erro compile vs 2013 (release and debug)

### ISSUE THREAD

**Issue by joseBarreto** [commontk/qt-easy-build#19] opened 2016-04-12 12:51 UTC
I'm getting this error when I try to run for vs2013 (release and debug)

![error prompt](https://cloud.githubusercontent.com/assets/11754960/14460447/f54a955e-0093-11e6-9a41-d94b062ca95a.png)

**Comment by dennis2society** [comment] 2016-04-13 09:34
Hi.
I am having the same problem (Windows 7, x64, VS2013) but get a different error:
```
# .......
Sources are in..............D:\dev\qt_src\qt-4.8.7-64-vs2013-deb
Build is done in............D:\dev\qt_src\qt-4.8.7-64-vs2013-deb
Install prefix..............D:\dev\qt_src\qt-4.8.7-64-vs2013-deb
Headers installed to........D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\include
Libraries installed to......D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\lib
Plugins installed to........D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\plugins
Imports installed to........D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\imports
Binaries installed to.......D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\bin
Docs installed to...........D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\doc
Data installed to...........D:\dev\qt_src\qt-4.8.7-64-vs2013-deb
Translations installed to...D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\translations
Examples installed to.......D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\examples
Demos installed to..........D:\dev\qt_src\qt-4.8.7-64-vs2013-deb\demos

Include paths...............d:/dev/qt_src/OpenSSL_1_0_1h-install-msvc1800-64/Deb
ug/include
Additional libraries........-Ld:/dev/qt_src/OpenSSL_1_0_1h-install-msvc1800-64/D
ebug/lib
Creating qmake...
Cleaning qmake failed, return code -1

CMake Error at build_qt_with_openssl.cmake:183 (message):

```
It also happens for both Debug and Release. 
I have tried to split the Powershell script into separate steps and skip downloading/unpacking of the cmake scripts to get some meaningful error messages (instead of "(message)..... ") which led to the same error posted by joseBarreto (error with ArgumentList).

**Comment by GuoJiechang** [comment] 2016-04-13 13:34
Hi,
I'm wondering if you have successfully build qt with VS2013 using this script?

**Comment by joseBarreto** [comment] 2016-04-13 13:43
Hi, I could not.

**Comment by GuoJiechang** [comment] 2016-04-13 13:50
Please, let me know if you success. I give up...after trying lots of time. Good luck.

**Comment by jcfr** [comment] 2016-04-13 13:54
Hi All, 

Thanks for the reports. I will do an other round of testing and post update shortly. 

Hang tight. 
Jc

**Comment by jcfr** [comment] 2016-04-13 14:49
@joseBarreto I am not able to reproduce the problem. I suggest you try to run the following in the VS2013 terminal:

```
@powershell -Command "Start-Process 'C:\D\Support\cmake-2.8.12.1-win32-x86\bin\cmake.exe' -ArgumentList '--version' -NoNewWindow -PassThru -Wait"
```

In my case, here is the output:

![image](https://cloud.githubusercontent.com/assets/219043/14497579/4bc0b20c-0165-11e6-946c-dda50b3be33a.png)

**Comment by jcfr** [comment] 2016-04-13 14:53
@dennis2society In your case, the configuration process is failing. See https://github.com/jcfr/qt-easy-build/blob/85feee54a277ca0b01e73c0bc1c5210e18e17a3d/cmake/build_qt_with_openssl.cmake#L169-L184

Could you confirm the destination folder (C:\Support) was empty ?

**Comment by GuoJiechang** [comment] 2016-04-13 15:00
@jcfr 
Hi.What about this error？

```
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\src\3rdparty\webkit\Source\WebCore\Make
file.WebKit [release] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\src\3rdparty\webkit\Source\Makefile.Web
Kit [sub-WebCore-make_default-ordered] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\Makefile [sub-webkit-make_default-order
ed] Error 2
CMake Error at QEBQt4ExternalProjectCommand.cmake:123 (message):
Problem building Qt
CMake Error at build_qt_with_openssl.cmake:197 (message):
```

**Comment by jcfr** [comment] 2016-04-13 15:06
@GuoJiechang the actual error is not reported here. I would suggest you:
- start the VS2013 64-bit console
- `cd C:\D\Support\qt-4.8.7-64-vs2013-rel`
- `jom`  # Make sure jom is in the path

Doing a serial build will stop at the first error and provide some more context.

**Comment by dennis2society** [comment] 2016-04-13 15:30
Hi. Thanks for the quick reaction.
The configuration error (line 183 in build_qt_with_openssl.cmake) occurs always and regardless of my destination folder (d:\dev\qt_src) being empty. Especially the qt-src download takes quite a while so I wanted to test if I can strip your Powershell script to skip the downloads which results in the same error. However the error is the same when running the Powershell line in an empty folder.
I should mention that I have (a newer version of) CMAKE already installed on my system and it is included in the Windows PATH. But I've seen in your script that it is explicitly using the downloaded version, so I don't expect this to be the problem.
Unfortunately there is no meaningful error message at all why the CMAKE configuration fails...

**Comment by jcfr** [comment] 2016-04-13 15:35
@dennis2society Thanks for providing additional details. 

Seems the issue is related to starting the CMake process. 

Could you run the command posted in https://github.com/jcfr/qt-easy-build/issues/19#issuecomment-209485389 and report back ?

**Comment by dennis2society** [comment] 2016-04-13 15:46
```
> d:\dev\qt_src>@powershell -Command "Start-Process 'd:\dev\qt_src\cmake-2.8.12.1-
win32-x86\bin\cmake.exe' -ArgumentList '--version' -NoNewWindow -PassThru -Wait"


cmake version 2.8.12.1
Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id ProcessName
-------  ------    -----      ----- -----   ------     -- -----------
     42       7     2052       4676    49     0,00   6136 cmake
Start-Process : Cannot process request because the process (6136) has exited.
At line:1 char:14
+ Start-Process <<<<  'd:\dev\qt_src\cmake-2.8.12.1-win32-x86\bin\cmake.exe' -A
rgumentList '--version' -NoNewWindow -PassThru -Wait
    + CategoryInfo          : NotSpecified: (:) [Start-Process], InvalidOperat
   ionException
    + FullyQualifiedErrorId : System.InvalidOperationException,Microsoft.Power
   Shell.Commands.StartProcessCommand
```

**Comment by jcfr** [comment] 2016-04-13 15:51
Et voila. There is now a minimal test to try to address the problem.

If you start a regular windows cmd line, can you run:

```
d:\dev\qt_src\cmake-2.8.12.1-win32-x86\bin\cmake.exe --version
```

?

**Comment by dennis2society** [comment] 2016-04-13 15:53
Works fine for both the normal CMD and VS2013 command prompt

**Comment by jcfr** [comment] 2016-04-13 16:03
Great. It means the issue causing error reported in https://github.com/jcfr/qt-easy-build/issues/19#issuecomment-209518866 is either:
- issue specific to CMake executable. 
- Credential associated with powershell
- Incorrect powershell syntax - may be you have a newer version ... 

Some idea to try:

1) 

```
@powershell -Command "Start-Process 'd:\dev\qt_src\cmake-2.8.12.1-
win32-x86\bin\cmake-gui.exe'  -NoNewWindow -PassThru -Wait"
```

2)

```
@powershell -Command "Start-Process 'calc.exe'  -NoNewWindow -PassThru -Wait"
```

**Comment by GuoJiechang** [comment] 2016-04-14 07:36
@jcfr 
Hi, I use the solution you provide, but meet the same error. 

The error code is followed. 
`return WEB_UI_STRING("Look Up "<selection>"", "Look Up context menu item with selected word").replace("<selection>", truncatedStringForLookupMenuItem(selectedString));`

The error report on the console
```
DefaultLocalizationStrategy.cpp
platform\DefaultLocalizationStrategy.cpp(327) : error C2065: “selection”: 未声
明的标识符(undeclared identifier)
platform\DefaultLocalizationStrategy.cpp(327) : error C2228: “.replace”的左边
必须有类/结构/联合(on the left of ‘replace’  must have a class / structure / joint)
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\WebCore\Make
file.WebKit.Debug [tmp\obj\debug_shared\DefaultLocalizationStrategy.obj] Error 2

jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\WebCore\Make
file.WebKit [debug] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\Makefile.Web
Kit [sub-WebCore-make_default-ordered] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\Makefile [sub-webkit-make_default-order
ed] Error 2
```

**Comment by dennis2society** [comment] 2016-04-14 08:40
@jcfr 
Both Powershell lines you suggested before (1. and 2.) work fine. Cmake gui and calc appear as expected.
Looks like the "ArgumentList" is causing problems here.
This is my Powershell version:

> PS D:\dev\qt_src> $PSVersionTable.PSVersion

Major  Minor  Build  Revision

---

2      0      -1     -1

**Comment by jcfr** [comment] 2016-04-15 18:53
Interestingly, I have the same version:

```
PS C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      -1     -1
```

**Comment by jcfr** [comment] 2016-04-15 19:31
@dennis2society 

Did you find syntax working on your setup ? As soon as we find something that work .. we could update the script.

@GuoJiechang 

>  I use the solution you provide, but meet the same error. 

May be you could try this: http://www.holoborodko.com/pavel/2011/02/01/how-to-compile-qt-4-7-with-visual-studio-2010/#comment-7246

Hth
Jc

**Comment by GuoJiechang** [comment] 2016-04-18 06:07
@jcfr Thanks a lot for helping me! I finally build ok.

**Comment by jcfr** [comment] 2016-04-18 13:38
>  Thanks a lot for helping me! I finally build ok.

@GuoJiechang  Great. Glad you managed to address the problem.
 Would you mind posting what was the solution ? That could be helpful for others. Thanks

**Comment by GuoJiechang** [comment] 2016-04-18 14:04
Yes. Of Course. After at least ten times attempts, I finally success.Here's some errors I met and solutions. I hope this will be helpful for you.

## First error

`platform\DefaultLocalizationStrategy.cpp(327) : error C2065: “selection”: 未声
明的标识符(undeclared identifier)
platform\DefaultLocalizationStrategy.cpp(327) : error C2228: “.replace”的左边
必须有类/结构/联合(on the left of ‘replace’ must have a class / structure / joint)
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\WebCore\Make
file.WebKit.Debug [tmp\obj\debug_shared\DefaultLocalizationStrategy.obj] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\WebCore\Make
file.WebKit [debug] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\Makefile.Web
Kit [sub-WebCore-make_default-ordered] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\Makefile [sub-webkit-make_default-order
ed] Error 2`

## Solution:

change the code in line 327 in DefaultLocalizationStrategy.cpp. There are some strange quotation mark, change it ,and add “\” before quotation mark.
change to the following:
`return WEB_UI_STRING("Look Up \"<selection>\"", "Look Up context menu item with selected word").replace("<selection>", truncatedStringForLookupMenuItem(selectedString));`

## Second error

`GraphicsLayerQt.cpp
        lib /NOLOGO  /OUT:debug\webcore.lib @C:\Users\GJC\AppData\Local\Temp\web
core.lib.4228.196593.jom
tmp\obj\debug_shared\DefaultLocalizationStratjom: C:\D\Support\qt-4.8.7-64-vs201
3-deb\src\3rdparty\webkit\Source\WebCore\Makefile.WebKit.Debug [debug\webcore.li
b] Error 1112
egy.obj : fatal error LNK1112: 模块计算机类型“x64”与目标jom: C:\D\Support\qt-4
.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\WebCore\Makefile.WebKit [debug] Er
ror 2
计算机类型“X86”冲突
(linking problem: fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'X86')
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\Makefile.Web
Kit [sub-WebCore-make_default-ordered] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-deb\Makefile [sub-webkit-make_default-order
ed] Error 2
CMake Error at QEBQt4ExternalProjectCommand.cmake:123 (message):
  Problem building Qt`

## Solution

No exact solution, I think maybe some times before, I used wrong console(32bit) to compile  and then I changed to 64bit console which may cause conflicts. So my solution is to delete all the files I downloaded and compiled before. 
Then success.
Good luck for all confused.

**Comment by dennis2society** [comment] 2016-04-20 12:06
@jcfr 
Haven't found a working syntax yet. It's even more confusing now....
This works fine:

> D:\dev\qt_src>@powershell -Command "Start-Process 'd:\dev\qt_src\cmake-2.8.12.1-win32-x86\bin\cmake.exe' -ArgumentList '--help' -NoNewWindow -PassThru -Wait"

while this does not:

> D:\dev\qt_src>@powershell -Command "Start-Process 'd:\dev\qt_src\cmake-2.8.12.1-win32-x86\bin\cmake.exe' -ArgumentList '--version' -NoNewWindow -PassThru -Wait"

Update 1: The second line works when I remove the "-Wait". Maybe it is finishing too fast for PS to notice.

Update 2: I have got so far as before and it still fails when configuring QT.  A closer look at the CMAKE output reveals that there are quite some paths broken (looks like multiple paths are mixed up due to cross-talk from output...). I am not sure if this related to the console output or if the strings are really broken within CMAKE. This is how it looks:

> Environment:
>     INCLUDE=
>       Unset
>     LIB=
>       Unset
>     PATH=
>       d:\ProgramData\Oracle\Java\javapath
> t     C:\Program Files (x86)\NVIDIA Corporateixoenc\uPthey:s XF\iCloem moorn
> h   i s   n oCt: \fPoruongdr a(mn mFaiklee)s
>  (x86)\Intel\iCLS Client\
> t     C:\Program Files\Inetxeelc\uitCeL:S  FCilliee notr\
> h   i s   n oCt: \fWoiunnddo w(sn\msaykset)e
> m32
>       C:\Windows
>       C:\Windows\System32\Wbem
>       C:\Windows\System32\WindowsPowerShell\v1.0\
>       C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
>       C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
>       C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
>       C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
>       C:\Program Files (x86)\CMake 2.8\bin
>       C:\Program Files\DependencyWalker
>       "C:\Program Files (x86)\NSIS"
>       "C:\Program Files (x86)\Java\jre7\bin"
>       C:\Program Files\doxygen\bin
>       C:\Program Files\doxygen\bin
>       "C:\Program Files (x86)\Graphviz2.36\bin"
> :     C:\ProgCrMaamk eF iElrerso r( xa8t6 )Q\EIBVQIt 4FEoxutnedrantailoPnr\oVjIeScAt\CWoimnmNaTn\dB.icnm\a
> 9 3   ( m e sCs:a\gPer)o:g
> r a mP rFoiblleesm\ IcVoIn fFioguunrdiantgi oQnt\
> V
> I

Update 3: I have found a possibly relevant line in the output that I wasn't aware until now:

> All the required DirectShow/Direct3D files couldn't be found.
> Make sure you have either the platform SDK AND the DirectShow SDK or the Windows SDK installed.
> If you have the DirectShow SDK installed, please make sure that you have run the <path to SDK>\SetEnv.Cmd script.
> vmr9.h not found
> dshow.h not found
> strmiids.lib not found
> dmoguids.lib not found
> msdmo.lib not found
> d3d9.h not found

I will install the Windows SDK and report again.

Update 4: As I just found out, the Windows SDK is already included in VS2013. I am running out of ideas...

**Comment by dennis2society** [comment] 2016-04-22 12:41
Good news! I think I got it running. 
The main problem was the %PATH% environment variable for my system. It contained a mixture of path entries that were quoted (for the whitespaces) and some others that were not. (Quotes were not added by myself but from other installers, e.g. some Intel storage software and TortoiseSVN).
Putting every entry in quotes did not help at all, but removing ALL quotes from the PATH line indeed fixed my problems. 
Now your one-liner powershell script works as expected.
Maybe the 'Don't put quotation marks in your PATH variable!' should be mentioned somewhere in a prominent place.

Update: OK. Debug build ran through just fine. I think this can be closed.

**Comment by jcfr** [comment] 2016-04-22 16:36
Great news. Thanks for the detailed report.

If you would like, you could do a PR to update the README and add a
"Frequently Asked Questions" section.

Let me know what you think,
Jc

**Comment by dennis2society** [comment] 2016-04-22 16:58
I will. Need some practice with git anyway.

**Comment by mingzhong163** [comment] 2016-05-03 10:17
help!! When I try to build QT4.8.7 from the source code, these errors were showed up as follows:
```
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\src\3rdparty\webkit\Source\WebCore\Make
file.WebKit [release] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\src\3rdparty\webkit\Source\Makefile.Web
Kit [sub-WebCore-make_default-ordered] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\Makefile [sub-webkit-make_default-order
ed] Error 2
CMake Error at QEBQt4ExternalProjectCommand.cmake:123 (message):
Problem building Qt
CMake Error at build_qt_with_openssl.cmake:197 (message):
```

My computer is equiped with win7 x64 and vs2013 x64. Who can help me? I have tried all kinds of ways described as above eg. guojiechang, dennis2society. Actually, I have tried the approach given by guojiechang, because we have encountered the same errors.

**Comment by GuoJiechang** [comment] 2016-05-03 15:31
@mingzhong163  Maybe you can try the branch
4.8.7-update-to-cmake-3.4.3 and choose default version to compile with VS2013. And don't forget to rewrite the code I mentioned above.

**Comment by mingzhong163** [comment] 2016-05-05 11:53
@GuoJiechang I appreciate for help. Then how can I obtain the 4.8.7-update-to-cmake-3.4.3 program? Or have you tried the branch? How does it work? I have tried more than 10 ways descirbed on the related webiste. Please tell me more detailedly.

**Comment by mingzhong163** [comment] 2016-05-05 14:50
@GuoJiechang I have found the branch 4.8.7-update-to cmake-3.4.3. Thanks! I am trying this approach. Hope it works!

**Comment by jcfr** [comment] 2016-05-05 15:02
Thanks @GuoJiechang for helping out :+1: 

@mingzhong163 As soon as your done with your test, I will integrate the change of `4.8.7-update-to-cmake-3.4.3`

**Comment by mingzhong163** [comment] 2016-05-06 09:44
@jcfr Actually, I have tried the branch 4.8.7-update-to-cmake-3.4.3, but exactly the same errors as in building qt with camke 2.8.12 showed up detailly as follows:

```
GraphicsContext.cpp
GraphicsLayer.cpp
Length.cpp
GraphicsTypes.cpp
Image.cpp
Gradient.cpp
LinkHash.cpp
ImageBuffer.cpp
正在生成代码...
Logging.cpp
ImageSource.cpp
MIMETypeRegistry.cpp
IntRect.cpp
Path.cpp
正在生成代码...
正在生成代码...
jom: D:\Qtbuild\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\WebCore\Makefi
le.WebKit [debug] Error 2
jom: D:\Qtbuild\qt-4.8.7-64-vs2013-deb\src\3rdparty\webkit\Source\Makefile.WebKi
t [sub-WebCore-make_default-ordered] Error 2
jom: D:\Qtbuild\qt-4.8.7-64-vs2013-deb\Makefile [sub-webkit-make_default-ordered
] Error 2
CMake Error at QEBQt4ExternalProjectCommand.cmake:123 (message):
  Problem building Qt


CMake Error at build_qt_with_openssl.cmake:197 (message):
```

My build enviroment is like this: **vs2013 update5, win7 x64bit.** Also, I build qt4.8.7 in **debug mode** using **vs2013 debug command prompt x64**, and **set the build directory in "D:\Qtbuild"** instead of "c:\d\support". There is no quotation mark in the system enviroment variable of %path% and no other errors described above. 
Now I am trying to use command prompt x64 with this branch in order to build qt. God bless me.

**Comment by zhouqlsaga** [comment] 2016-05-11 06:05
I met with the same problem with @mingzhong163 . Does anyone know how this happened and how to solve it?

**Comment by jcfr** [comment] 2016-05-11 06:18
((Ps: Note that I will be travelling until beginning of next week and will have limited access to email ))

Looks like the issue happen when building Qt.

Keeping the build tree as it is, what is the error message when you try the following:
1. Open `vs2013 debug command prompt x64`
2. `cd D:\Qtbuild\qt-4.8.7-64-vs2013-deb`
3. `jom`

That should give you hint about the problem. Using your favorite search engine to learn about the error should also be helpful.

I also have no idea of the meaning of `正在生成代码...`

Could it be related to the `code page` and/or `system locale` associated with your system ?  See http://serverfault.com/questions/80635/how-can-i-manually-determine-the-codepage-and-locale-of-the-current-os

On my system, running `chcp` reports:

```
Active code page: 437
```

and running `systeminfo` output:

```
[...]
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
[...]
```

**Comment by zhouqlsaga** [comment] 2016-05-11 07:33
@jcfr  Thank you for your time in travelling. This is not very urgent and you can reply it when it's convinient.

"正在生成代码..." means generating code...
I tried the method @jcfr showed, only got an error report "Error: File Makefile doesn't exist".
Besides, I don't think this problem has anything to do with the system location, since @GuoJiechang  succeeded in compiling. 

And I assume that this either related to the cmake version or the Visual Studio 2013 version, There has to be something wrong.

**Comment by qimo601** [comment] 2016-07-13 12:52
CMake Error at QEBQt4ExternalProjectCommand.cmake:123 (message): Problem building Qt
CMake Error at build_qt_with_openssl.cmake:197 (message):
![1](https://cloud.githubusercontent.com/assets/5515564/16803757/c3dba19e-493a-11e6-86bb-bc33130c134b.png)

I found the same problem,when i excute the script“Visual Studio 2013 64-bit Debug”.
can any body help me?

My Environment is win7-64bit  + qt4.8.7 + vs2013

**Comment by jcfr** [comment] 2016-07-13 14:43
@qimo601 I suspect the issue is related to the locals ... could you try running `chcp` and `systeminfo` as described in https://github.com/jcfr/qt-easy-build/issues/19#issuecomment-218371765

**Comment by summerbatman** [comment] 2016-12-06 23:44
@mingzhong163 do you succeed finally?

**Comment by summerbatman** [comment] 2016-12-07 04:35
![image](https://cloud.githubusercontent.com/assets/18416140/20954791/43d70cba-bc79-11e6-9e93-2af58fb9f018.png)
does anybody solve this problem successfully? please help me.

**Comment by jcfr** [comment] 2016-12-08 19:39
@summerbatman I do not know if @qimo601 came up with a solution. 

That said as soon as there is a fix for this, I would be happy to review it and integrate it.

**Comment by gildoringlorin** [comment] 2017-10-12 02:04
start the VS2013 64-bit console
cd C:\D\Support\qt-4.8.7-64-vs2013-rel
jom # Make sure jom is in the path

@jcfr,hi,are you still there?when I type 'jom' and enter,it said that 'jom is not a command'.and I don't find jom in the path,what's the problem of this?

**Comment by jcfr** [comment] 2017-10-12 02:20
Hi, 

By *make sure jom is in the PATH*, I meant the following set of commands:

- start the VS2013 64-bit console
- `cd C:\D\Support\qt-4.8.7-64-vs2013-rel`
- `set PATH=C:\D\Support\qt-4.8.7-64-vs2013-rel\jom_1_1_0;%PATH%`    # This will ensure jom is in the PATH
- `jom` 

Let me know how it goes and if that helps

**Comment by gildoringlorin** [comment] 2017-10-12 02:42
thanks for replying.
I will let you konw as soon as I tried.

**Comment by gildoringlorin** [comment] 2017-10-12 06:57
![default](https://user-images.githubusercontent.com/18072819/31482926-e6020040-af5c-11e7-9fda-cf5397a97575.png)
in path C:\D\Support,there is no folder named 'qt-4.8.7-64-vs2013-rel', is it normal?

**Comment by jcfr** [comment] 2017-10-12 07:01
@gildoringlorin  the suffix will be different for Release and Debug build.

* `qt-4.8.7-64-vs2013-rel` -> Release build
* `qt-4.8.7-64-vs2013-deb` -> Debug build

**Comment by gildoringlorin** [comment] 2017-10-12 07:08
I see,should have known it before...it's quite obvious

**Comment by gildoringlorin** [comment] 2017-10-12 07:40
sorry, I wonder if I catch the point of your intention, cause I konw little about cmake and cmd command.
still got the error.
![default](https://user-images.githubusercontent.com/18072819/31484613-8ece153c-af63-11e7-9576-893045bcbb50.png)

I manually add ''C:\D\Support\qt-4.8.7-64-vs2013-deb\jom_1_1_0" in the system envionment variables path.
- %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\SlikSvn\bin;**C:\D\Support\qt-4.8.7-64-vs2013-deb\jom_1_1_0**

besides, folder 'jom_1_1_0' didn't exist in 'qt-4.8.7-64-vs2013-deb', is it right?

**Comment by gildoringlorin** [comment] 2017-10-12 11:59
@jcfr. alright, forget about the 'jom' problem, I solved the compile error referring to GuoJiechang's comment. but there are two errors need to be fixed().

**first**

DefaultLocalizationStrategy.cpp:325
`return formatLocalizedString(WEB_UI_STRING("Look Up **\"%@\"**", "Look Up context menu item with selected word"), selectedCFString.get(quotation mark));
`
**second**

DefaultLocalizationStrategy.cpp:327

`return WEB_UI_STRING("Look Up **\"<selection>\"**", "Look Up context menu item with selected word").replace("<selection>", truncatedStringForLookupMenuItem(selectedString));`

**Comment by jcfr** [comment] 2017-10-12 13:42
Good to see you are making progress.

To suggest something, in addition of the filename and line, I suggest you also copy here the build errors.

**Comment by gildoringlorin** [comment] 2017-10-13 00:45
I forgot. the build errors are just the same as someone above.

```
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\src\3rdparty\webkit\Source\WebCore\Make
file.WebKit [release] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\src\3rdparty\webkit\Source\Makefile.Web
Kit [sub-WebCore-make_default-ordered] Error 2
jom: C:\D\Support\qt-4.8.7-64-vs2013-rel\Makefile [sub-webkit-make_default-order
ed] Error 2
CMake Error at QEBQt4ExternalProjectCommand.cmake:123 (message):
Problem building Qt
CMake Error at build_qt_with_openssl.cmake:197 (message):
```

to solve this problem, change two quotation mark in DefaultLocalizationStrategy.cpp

**first**

DefaultLocalizationStrategy.cpp:325
return formatLocalizedString(WEB_UI_STRING("Look Up **\"%@\"**", "Look Up context menu item with selected word"), selectedCFString.get(quotation mark));

**second**

DefaultLocalizationStrategy.cpp:327

return WEB_UI_STRING("Look Up `\"<selection>\"`", "Look Up context menu item with selected word").replace("<selection>", truncatedStringForLookupMenuItem(selectedString));

**Comment by carlos-luque** [comment] 2017-12-08 21:56
Hello
  
 I am having the same error as dennin2society. I checked all steps explained in this thread but I cannot fix it. 
 
The error is 
` Sources are in..............C:\D\Support\qt-4.8.7-64-vs2013-rel
Build is done in............C:\D\Support\qt-4.8.7-64-vs2013-rel
Install prefix..............C:\D\Support\qt-4.8.7-64-vs2013-rel
Headers installed to........C:\D\Support\qt-4.8.7-64-vs2013-rel\include
Libraries installed to......C:\D\Support\qt-4.8.7-64-vs2013-rel\lib
Plugins installed to........C:\D\Support\qt-4.8.7-64-vs2013-rel\plugins
Imports installed to........C:\D\Support\qt-4.8.7-64-vs2013-rel\imports
Binaries installed to.......C:\D\Support\qt-4.8.7-64-vs2013-rel\bin
Docs installed to...........C:\D\Support\qt-4.8.7-64-vs2013-rel\doc
Data installed to...........C:\D\Support\qt-4.8.7-64-vs2013-rel
Translations installed to...C:\D\Support\qt-4.8.7-64-vs2013-rel\translations
Examples installed to.......C:\D\Support\qt-4.8.7-64-vs2013-rel\examples
Demos installed to..........C:\D\Support\qt-4.8.7-64-vs2013-rel\demos

Include paths...............C:/D/Support/OpenSSL_1_0_1h-install-msvc1800-64/Rele
ase/include
Additional libraries........-LC:/D/Support/OpenSSL_1_0_1h-install-msvc1800-64/Re
lease/lib
Creating qmake...
Cleaning qmake failed, return code -1

CMake Error at build_qt_with_openssl.cmake:183 (message): `

This command works.

`C:\D\Support>powershell -Command "Start-Process 'C:\D\Support\cmake-2.8.12.1-win
32-x86\bin\cmake.exe' -ArgumentList '--version' -NoNewWindow -PassThru -Wait"
cmake version 2.8.12.1

Handles  NPM(K)    PM(K)      WS(K) VM(M)   CPU(s)     Id ProcessName
-------  ------    -----      ----- -----   ------     -- -----------
     19       3      420       1756    12     0.02   7620 cmake`

I checked my %PATH% and it doesn't have quotes. 
I don't know how I can fix this error. Could anybody help me to fix it?

**Comment by idhamari** [comment] 2018-03-26 15:13
Here is what I did:

1. Install Windows 10 (sometimes there are conflicting paths, programs, .. etc ). Installing clean windows is faster than trying to solve different problems or waiting for help.
2. Install VisualStudio 2013 Community with Update 4.
3. Run C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\Shortcuts\VS2013 x64 Native Tools Command Prompt
4. Copy paste the script to the command line opened in step 3.

**Comment by jcfr** [comment] 2020-09-29 22:06
Our apologies for the late follow up.

Closing as current efforts are geared toward maintaining build for Qt 5.15.1 on Linux and macOS.

That said, contributions are welcome.

**Closed as completed by jcfr** 2020-09-29 22:06 UTC
Labels: bug
